### ISSUE TITLE
Blog Feedback

### ISSUE THREAD

**Issue by cjmanetta** [ChristineSchatz/ChristineSchatz.github.io#7]
Hey Christine,

Love your subtle background and your color choices! Just a little thing on the blog pages, the container that holds the main content has a height on it which boxes in your posts so that you have to do a lot more scrolling to read them. I would recommend taking off the height to give the content a little more space to flow. Great work!

Best,

Charlotte

**Comment by ChristineSchatz** [comment]
@cjmanetta Thank you so much for your comments! You're totally right about the blog scrolling. It looks pretty terrible on a big monitor (I've been working mostly with a 13-inch). Gotta change that pronto! :)
